# Generated by Django 3.1.6 on 2021-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatquestion', models.CharField(max_length=1000)),
                ('userreply', models.CharField(max_length=1000)),
                ('defaultreply', models.CharField(max_length=1000)),
                ('answer', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=5)),
            ],
        ),
    ]
