# Generated by Django 3.1.6 on 2021-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatquestion', models.CharField(max_length=1000)),
                ('userreply', models.CharField(max_length=1000)),
                ('defaultreply', models.CharField(max_length=1000)),
                ('answer1', models.CharField(max_length=1000)),
                ('answer2', models.CharField(max_length=1000)),
                ('correctanswer', models.CharField(max_length=1000)),
            ],
        ),
    ]
