# Generated by Django 3.1.6 on 2021-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='answer21',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='answer22',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='answer31',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='answer32',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chatquestion2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chatquestion3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='correctanswer2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='correctanswer3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
