# Generated by Django 3.1.6 on 2021-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receivericon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='sendericon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
