# Generated by Django 3.1.6 on 2021-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forstaelse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=1000)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=5)),
                ('explanation', models.CharField(max_length=1000)),
            ],
        ),
    ]
