# Generated by Django 3.1.6 on 2021-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forstaelse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forstaelse',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='forstaelse',
            old_name='chat',
            new_name='chat1',
        ),
        migrations.RenameField(
            model_name='forstaelse',
            old_name='explanation',
            new_name='explanation1',
        ),
        migrations.RenameField(
            model_name='forstaelse',
            old_name='question',
            new_name='question1',
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='answer2',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], max_length=5),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='answer3',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], max_length=5),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='chat2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='chat3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='explanation2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='explanation3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='question2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='forstaelse',
            name='question3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
