# Generated by Django 3.1.6 on 2021-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RyddeSetninger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word2', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word3', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word4', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word5', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word6', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word7', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word8', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word9', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
                ('word10', models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20)),
            ],
        ),
    ]
