# Generated by Django 3.1.6 on 2021-03-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rydde_setninger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word10',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word4',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word5',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word6',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word7',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word8',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word9',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=20),
        ),
    ]
