# Generated by Django 3.1.6 on 2021-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rydde_setninger', '0002_auto_20210317_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass1',
            field=models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], default='Null', max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass10',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass2',
            field=models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], default='Null', max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass3',
            field=models.CharField(choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], default='Null', max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass4',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass5',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass6',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass7',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass8',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AddField(
            model_name='ryddesetninger',
            name='wordClass9',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word10',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='word9',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
