# Generated by Django 3.1.6 on 2021-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rydde_setninger', '0004_ryddesetninger_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ryddesetninger',
            name='wordClass1',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='wordClass2',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ryddesetninger',
            name='wordClass3',
            field=models.CharField(blank=True, choices=[('n', 'Substantiv'), ('v', 'Verb'), ('adj', 'Adjektiv'), ('adv', 'Adverb'), ('prp', 'Preposisjon'), ('conj', 'Konjuksjon'), ('subj', 'Subjuksjon'), ('det', 'Determinativ'), ('pron', 'Pronomen'), ('intj', 'Interjeksjon')], max_length=12),
        ),
    ]
