# Generated by Django 3.1.6 on 2021-03-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forstaelse', '0002_auto_20210226_1657'),
        ('chat', '0002_auto_20210308_1607'),
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='chat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat1', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='chat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat2', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='forstaelse1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forstaelse1', to='forstaelse.forstaelse'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='forstaelse2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forstaelse2', to='forstaelse.forstaelse'),
        ),
    ]
