# Generated by Django 3.1.6 on 2021-03-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forstaelse', '0002_auto_20210226_1657'),
        ('chat', '0002_auto_20210308_1607'),
        ('sets', '0002_auto_20210308_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='chat3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat3', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='sets',
            name='chat4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat4', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='sets',
            name='chat5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat5', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='sets',
            name='forstaelse3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forstaelse3', to='forstaelse.forstaelse'),
        ),
        migrations.AddField(
            model_name='sets',
            name='forstaelse4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forstaelse4', to='forstaelse.forstaelse'),
        ),
        migrations.AddField(
            model_name='sets',
            name='forstaelse5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forstaelse5', to='forstaelse.forstaelse'),
        ),
    ]
