# Generated by Django 3.1.6 on 2021-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0006_auto_20210326_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sets',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
