# Generated by Django 3.1.6 on 2021-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0007_auto_20210327_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sets',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
