# Generated by Django 3.1.6 on 2021-04-07 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sets', '0012_auto_20210404_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.sets')),
            ],
            options={
                'unique_together': {('owner', 'sets')},
            },
        ),
    ]
