# Generated by Django 3.1.6 on 2021-04-11 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sets', '0013_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sets.sets')),
            ],
            options={
                'unique_together': {('owner', 'sets')},
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
