# Generated by Django 3.1.6 on 2021-04-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0014_auto_20210411_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
