# Generated by Django 3.1.6 on 2021-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0018_auto_20210412_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
