# Generated by Django 3.1.6 on 2021-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0020_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='score',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
