# Generated by Django 3.1.6 on 2021-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0021_completed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='title',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
