# Generated by Django 3.1.6 on 2021-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0022_completed_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='setOwner',
            field=models.CharField(default='username', max_length=30),
            preserve_default=False,
        ),
    ]
