# Generated by Django 3.1.6 on 2021-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0023_completed_setowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='setOwner',
            field=models.CharField(default='username', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved',
            name='title',
            field=models.CharField(default='username', max_length=50),
            preserve_default=False,
        ),
    ]
